SIZE = 1024
FORMAT = "utf8"
DISCONNECT_MSG = "!DISCONNECT"
NB_CONNECTION = 10
SERVER = 'localhost'
CODE_USERNAME = "[USERNAME] "

CODES = {
    USERNAME : "[USERNAME] ",
    JOIN_CANAL : "[JOIN_CANAL] ",
    DISCONNECT_MSG : "!DISCONNECT"
}